### ISSUE TITLE
[Idea] Collapse/delete variables

### ISSUE THREAD

**Issue by equinusocio** [jonathanharrell/hiq#28]
I think some variables groups can be collapsed or removed to simplify the customization and clean code structure.

**Comment by jonathanharrell** [comment]
Can you give an example of a variable group that you would simplify?

**Comment by equinusocio** [comment]
```css
  /* font families */
--font-family-sans-serif: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen-Sans, Ubuntu, Cantarell, 'Helvetica Neue', sans-serif;
--font-family-serif: Georgia, 'Times New Roman', Times, serif;
--font-family-monospace: Menlo, Monaco, Consolas, 'Courier New', monospace;
--base-font-family: var(--font-family-sans-serif);
```

Why using a `--base-font-family` variable if you can directly use others.


```css

  /* font weights */
  --font-weight-light: 300;
  --font-weight-normal: 400;
  --font-weight-medium: 500;
  --font-weight-semibold: 600;
  --font-weight-bold: 700;

  /* letter spacing */
  --letter-spacing-base: -0.025em;

  /* applied font weights */
  --font-weight-base: var(--font-weight-normal);
  --heading-font-weight: var(--font-weight-medium);
  --strong-font-weight: var(--font-weight-semibold);
  --bold-font-weight: var(--font-weight-semibold);
  --definition-list-title-font-weight: var(--font-weight-semibold);
--input-font-weight: var(--font-weight-normal);
```

Why having the ` /* applied font weights */` variables group if we can directly use the variables from the first group. The `<strong>` element can directly use the `--font-weight-bold`  variable.

**Comment by jonathanharrell** [comment]
Say you are creating a new component and want to set the font family to whatever the base font family is that was set on the `body`. You don't want to look up the specific font family. You can use `--font-family-base`. The also allows you to define font families fewer times. Just define it once as the base, and then references that in multiple components.

The same is true of the font weights. Set a base that is used in most parts of your application, then references that when needed.

I like giving greater customization through variables overrides rather than forcing someone to override on the element itself. The way it is currently constructed if you define `--strong-font-weight`, your css doesn't actually change on the `strong` element. It is always:

`font-weight: var(--strong-font-weight, var(--font-weight-bold, 700));`

If, however, you remove the `--strong-font-weight` variable you might end up having:

strong {
   ~~font-weight: var(--font-weight-bold);~~
   font-weight: var(--font-weight-medium);
}

I prefer offering more variables and ending up with a cleaner stylesheet that uses fallbacks.

**Comment by equinusocio** [comment]
But `--font-family-base` is inside the configurations variables, i can set it, so i know its value. Following your thought the `--base-**` variables should not be configurables.

If i want to make a component and i need to overwrite the font-family i can just write `font-family: var(--font-family-sans-serif)` since i know that  `--base-font-family` is equal to (--font-family-sans-serif). Where is the differents? 

Consider that more variables = more configurations = more confusion.  

Also why i should have `--strong-font-weight` different from `--font-weight-bold`?!

**Comment by jonathanharrell** [comment]
Regarding the second point, you may want to use `--font-weight-medium` for `--strong-font-weight`. Many typefaces look better using the medium weight instead of bold for certain elements.

For the first point, consider the case of color variables. You can define a color as `--red: red` which is semantically clear. Then you can use that color in `--color-danger: var(--red)`.

It is essentially the same for `--font-family-sans-serif: Arial` and then `--font-family-base: var(--font-family-sans-serif`. The first is semantically clear and essentially just a wrapper for the value. You can use that wherever you need to. `--font-family-base` sets the font family on the entire body and conveys that is the base for the website/application. You don't have to override it on the `body` element yourself.

**Comment by jonathanharrell** [comment]
In general I agree with your point on configuration, but also think there are benefits to having the power to configure a large amount of styles from one variables file.

**Comment by jonathanharrell** [comment]
It could be that `--font-family-base` should instead be `--font-family-body` and `--font-weight-base` should be `--font-weight-body`.

**Comment by equinusocio** [comment]
I agree with you but right now there are a lot of redundant variables that does not add value to the configuration. I think we can make space for other variables. 

Also having global variables for all thing is not always a good choise. I think we need to think more component like. Like making css API for each component/element. I will add an example tomorrow :)

**Comment by equinusocio** [comment]
> Regarding the second point, you may want to use --font-weight-medium for --strong-font-weight. Many typefaces look better using the medium weight instead of bold for certain elements.

If i need/want to use the medium weight somewhere i will just use the --font-weight-medium setting :) why i should set the strong variables with another setting that doesn’t match the semantic of the variable name. 

I can also set a font-weight-light to 700. This is called inconsistency.

**Comment by jonathanharrell** [comment]
Overall I agree with the need to balance simplicity of configuration with the power to modify as much as possible through variables. We can find a way to balance the two.

**Comment by jonathanharrell** [comment]
Started simplifying some variables in b732c90163a0f1b6f77a4d186f833f068e2d8f23.

**Comment by jonathanharrell** [comment]
Some simplification of variables in 2.0.0-beta.
